# Generated by Django 3.1 on 2020-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20200903_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allurl',
            name='short_url',
            field=models.CharField(max_length=6),
        ),
    ]
