# Generated by Django 3.1 on 2020-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_auto_20200904_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allurl',
            name='short_url',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
